version: "3.7"  # Updated for better network support

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "80:80"
    depends_on:
      - kafka
    networks:
      - stream_net

  zookeeper: 
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - stream_net

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - stream_net

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_NAME=Sandbox Kafka Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - 8787:8080
    depends_on:
      - kafka
    networks:
      - stream_net

  ksql:
    container_name: ksqldb-server
    image: confluentinc/ksqldb-server:latest
    depends_on:
      - kafka
    ports:
      - 8788:8088
    environment:
      - KSQL_LISTENERS=http://0.0.0.0:8088
      - KSQL_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - stream_net

networks:
  stream_net:  # Defining the custom network
